name: .NET Core CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install ICU
      run: sudo apt-get install -y libicu-dev
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.0'
    - name: Build
      run: dotnet build src/Cultura_New/ultura_New.sln --configuration Release
    - name: Test
      run: dotnet test src/Cultura_New/Cultura_New.sln --configuration Release --no-build